// <auto-generated />
namespace GestionTicket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class login_usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(login_usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "202111051633353_login_usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
